'''
THIS FILE CONTAINS USEFUL CONSTANT TO MODIFY THE GAME ENVIROLMENT
'''

DIMCOW=(310, 510) #dimension of cowboy image
DIMTOMB=(300, 300) #dimension of tombstone image
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600
